**NUMPY**

In [2]:
import numpy as np

In [ ]:
#Create array without numpy
import array as arr
arr2 = arr.array('i',[1,2,3,4,5]) #array with integers
print(arr2)

array('i', [1, 2, 3, 4, 5])


In [ ]:
arr1 = np.array([1,2,3])  #create an array using numpy, more efficient
print(arr1)
print(type(arr1))
print(arr1.size)  #size of array - linear
print(arr1.ndim)  #dimensions of array
print(arr1.dtype) #data-type of array, usually 64-bit includes integers and float

[1 2 3]
<class 'numpy.ndarray'>
3
1
int64


**Saving space**

In [ ]:
arr3 = np.array([120,50,100],dtype='int8')  #use int8 to save space
print(arr3.dtype)

int8


In [ ]:
arr4 = np.array([[1,2,3],[4,5,6]])  #2-d array, 2x3
print(arr4)
print(arr4.size)
print(arr4.ndim)  #shows a 2-d array

[[1 2 3]
 [4 5 6]]
6
2


In [ ]:
arr5 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])  #3-d array
print(arr5)
print(arr5.size)
print(arr5.ndim)  #shows a 3-d array
print(arr5.shape) #2x2x3 matrix

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
12
3
(2, 2, 3)


**Accessing an element**

In [ ]:
print('2nd element in 1st row: ', arr4[0][1]) #access the element

2nd element in 1st row:  2


In [ ]:
print(arr1)
print(arr1[0:2])  #slicing 1-d array from 0 to 2

print(arr1[-3:-1])  #from end-3 to end-1

print(arr1[1:4:2])  #step of 2 from 1 to 4

print(arr1[::2])  #step of 2 from 1 to end

[1 2 3]
[1 2]
[1 2]
[2]
[1 3]


In [ ]:
arr6 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2x4 matrix
print(arr6[1,1:4]) #2nd row, 2nd to 5th element, doesnt include 5th element

arr7 = arr6[1,0:1]  #0 to 1, doesnt include 1st element
print(arr7)

[7 8 9]
[6]


**Making a copy**

In [ ]:
x = arr1.copy()  #copy of arr1, and not arr1 anymore
print(x)
arr1[0]=42
print(arr1)
print(x)
arr1[1]=5   #copy has an update?
print(x)

[42  5  3]
[42  5  3]
[42  5  3]
[42  5  3]


**Reshaping**

In [4]:
arr8 = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1-D array
arr9 = arr8.reshape(2,2,3)  #reshape the array
#print(arr9.shape)
print(arr9)
arr9[0][0][0] = 50
print(arr8)
print(arr9)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[50  2  3  4  5  6  7  8  9 10 11 12]
[[[50  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Accessing individual element and indices**

In [10]:
#for x in arr8:  #printing each element
#  print(x)

for x in arr9:
  #print(x)    #prints each matrix and not elements
  for y in x:
    print(y)

#print using nditer, can be used if we do not know the size of array
print("Printing using nditer")
for x in np.nditer(arr9):
  print(x)


[50  2  3]
[4 5 6]
[7 8 9]
[10 11 12]
Printing using nditer
50
2
3
4
5
6
7
8
9
10
11
12


In [11]:
#print using index
print("Printing using denumerate")
for idx, x in np.ndenumerate(arr9):
  print(idx,x)

Printing using denumerate
(0, 0, 0) 50
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


**Joining Arrays**

In [13]:
arr10 = np.array([1,2,3,4])
arr11 = np.array([5,6,7,8])
arr13 = np.concatenate((arr10,arr11))
print(arr13)

[1 2 3 4 5 6 7 8]


In [19]:
arr14 = np.array([[1,2],[3,4]]) #2x2 array
arr15 = np.array([[5,6],[7,8]]) #2x2 array
arr16 = np.concatenate((arr14,arr15), axis = 1) #concatenate across axis of 1, merges arrays, final=2x4, added columns
print(arr16)
arr17 = np.concatenate((arr14,arr15),axis=0)  #concatenate across axis of 0, adds arrays, final=4x2, added rows
print(arr17)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**Filtering**

In [22]:
arr18 = np.array([41,42,43,44]) #initial array
even_filter = [False,True,False,True] #boolen array
arr18_after_filt1 = arr18[even_filter]  #filtered the array based on filter
print(arr18_after_filt1)

[42 44]


In [23]:
arr19 = np.array([1,2,3,4,5,6,7,8,9,10])
arr19_filt1 = (arr19%2 == 0)  #Create the filter condition, gives boolean array
print(arr19[arr19_filt1])

[ 2  4  6  8 10]


In [25]:
#filtering on a matrix
arr20 = np.array([1,2,3,4,5,6])
arr21 = arr20.reshape(2,3)
print(arr21)
arr22_filt = (arr21%2==0)
print(arr21[arr22_filt])

[[1 2 3]
 [4 5 6]]
[2 4 6]
