**NUMPY**

In [1]:
import numpy as np

In [5]:
#Create array without numpy
import array as arr
arr2 = arr.array('i',[1,2,3,4,5]) #array with integers
print(arr2)

array('i', [1, 2, 3, 4, 5])


In [12]:
arr1 = np.array([1,2,3])  #create an array using numpy, more efficient
print(arr1)
print(type(arr1))
print(arr1.size)  #size of array - linear
print(arr1.ndim)  #dimensions of array
print(arr1.dtype) #data-type of array, usually 64-bit includes integers and float

[1 2 3]
<class 'numpy.ndarray'>
3
1
int64


In [14]:
arr3 = np.array([120,50,100],dtype='int8')  #use int8 to save space
print(arr3.dtype)

int8


In [21]:
arr4 = np.array([[1,2,3],[4,5,6]])  #2-d array, 2x3
print(arr4)
print(arr4.size)
print(arr4.ndim)  #shows a 2-d array

[[1 2 3]
 [4 5 6]]
6
2


In [24]:
arr5 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])  #3-d array
print(arr5)
print(arr5.size)
print(arr5.ndim)  #shows a 3-d array
print(arr5.shape) #2x2x3 matrix

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
12
3
(2, 2, 3)


In [25]:
print('2nd element in 1st row: ', arr4[0][1]) #access the element

2nd element in 1st row:  2


In [31]:
print(arr1)
print(arr1[0:2])  #slicing 1-d array from 0 to 2

print(arr1[-3:-1])  #from end-3 to end-1

print(arr1[1:4:2])  #step of 2 from 1 to 4

print(arr1[::2])  #step of 2 from 1 to end

[1 2 3]
[1 2]
[1 2]
[2]
[1 3]


In [35]:
arr6 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2x4 matrix
print(arr6[1,1:4]) #2nd row, 2nd to 5th element, doesnt include 5th element

arr7 = arr6[1,0:1]  #0 to 1, doesnt include 1st element
print(arr7)

[7 8 9]
[6]


In [42]:
x = arr1.copy()  #copy of arr1, and not arr1 anymore
print(x)
arr1[0]=42
print(arr1)
print(x)
arr1[1]=5   #copy has an update?
print(x)

[42  5  3]
[42  5  3]
[42  5  3]
[42  5  3]
