**Q1**

What will be the shape of the following NumPy array?



import numpy as np

arr = np.random.randint(1, 101, 100).reshape(10, -1)

In [ ]:
import numpy as np

arr = np.random.randint(1, 101, 100).reshape(10, -1)
#The -1 in the reshape, means size should be inferred based on the original size and specified dimensions
# 100 elements are reshaped into 10 rows, resulting in 10x10

print(arr.shape)

(10, 10)


**Q2**

What is the result of the following code?



import numpy as np

A = np.array([1, 2, 3])

B = A * 2

In [ ]:
A = np.array([1, 2, 3])

B = A * 2

print(B)

[2 4 6]


**Q3**

What does the following code output?



import numpy as np

matrix = np.eye(4)

result = np.diagonal(matrix)

print(result)

In [ ]:
matrix = np.eye(4)

result = np.diagonal(matrix)

print(result)

[1. 1. 1. 1.]


**Q4**

What is the result of the following code?



import numpy as np

A = np.array([[1, 2], [3, 4]])

B = A.T

In [ ]:
A = np.array([[1, 2], [3, 4]])

B = A.T
print(B)

[[1 3]
 [2 4]]


**Q5**

Which function can be used to concatenate two NumPy arrays horizontally?
p.hstack()

And not p.vstack(), np.concatenate, or np.append()

**Q6**

Which of the following functions can be used to compute the element-wise multiplication of two arrays A and B?

np.multiply(A,B)

**Q7**

What is the result of the following code?



import numpy as np

A = np.array([10, 20, 30, 40])

mask = (A >= 20) & (A <= 30)

B = A[mask]

In [ ]:
A = np.array([10, 20, 30, 40])

mask = (A >= 20) & (A <= 30)

B = A[mask]
print(B)

[20 30]


**Q9**

Which of the following NumPy functions will return the indices of the minimum and maximum values in an array?


np.argmin(), np.argmax()

**Q10**

What is the output of the following code?



import numpy as np

arr = np.arange(1, 10).reshape(3, 3)

result = np.trace(arr)

print(result)

In [ ]:
arr = np.arange(1, 10).reshape(3, 3)

result = np.trace(arr)  #trace gives sum along diagnal
print(arr)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


**Q11**

What is the output of the following code?



import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

[-3  6 -3]


**Q12**

Write a Python program using NumPy to create a 5x5 matrix filled with random integers between 1 and 100. Calculate the mean and standard deviation of the matrix and print them.

In [ ]:
q12 = np.random.randint(1,100,25).reshape(5,5)
print(q12)
print(q12.mean()) #mean
print(q12.std())

[[74 30 43 81 33]
 [73 15 74 11 25]
 [26 37 38 53 12]
 [20 92 72 29  1]
 [ 9 46 11 25 84]]
40.56
26.72389193212695


**Q13**

Using NumPy, create a 5x5 identity matrix and add a scalar value of 5 to it. Multiply the resulting matrix with a 5x1 column vector filled with random integers between 1 and 10. Print the resulting vector.

In [3]:
import numpy as np

matrix1 = np.eye(5)
matrix1 = matrix1 + 5
matrix2 = np.random.randint(1,10,5)
matrix3 = np.matmul(matrix1,matrix2)
print(matrix3)

[ 97.  97. 102.  96. 102.]


**Q14**

Write a Python program using NumPy to create two 3x3 matrices filled with random integers between 1 and 100. Compute their element-wise multiplication, and print the resulting matrix.

In [6]:
import numpy as np

matrix1 = np.random.randint(1,100,9).reshape(3,-1)
matrix2 = np.random.randint(1,100,9).reshape(3,-1)
matrix3 = np.multiply(matrix1,matrix2)
print(matrix3)

[[1034  135 2490]
 [1288 3132 2880]
 [ 690  752 2964]]


**Q15**

Using NumPy, create a 1000-element array of random integers between 1 and 1000. Calculate the cumulative sum of the array and print the 10th, 100th, and 500th elements of the cumulative sum array.

In [1]:
import numpy as np

array = np.random.randint(1,1000,1000)

sum = 0
for x in array:
  x = x+sum
  sum=x

print([array[9], array[99], array[499]])

[369, 627, 224]


**Q16**

Write a Python program using NumPy to create a 10x10 matrix filled with random integers between 1 and 100. Find the minimum and maximum values of the matrix along with their indices.

In [3]:
import numpy as np

array = np.random.randint(1,100,100).reshape(10,-1)

print(array)
print(np.unravel_index(np.argmax(array,axis=None),array.shape))
print(np.unravel_index(np.argmin(array,axis=None),array.shape))

[[ 8  1 61 94  6 96 42 88 89 46]
 [51 76 78 20 36 38 15 25 75 77]
 [67 38 49 77 42 38 17 87 37 11]
 [35 53 90 39 31 90  8 66  1 19]
 [73 34 85 66  9 21 52 99 72  9]
 [64 16 61 10 65 93 18 65  5 11]
 [67 89 21 38 30 64 24 38 39 73]
 [25 43 24 74 10 25 35 30 31 48]
 [ 3 96 40 34 41 46 73 76 36 40]
 [74 93  1 65 28 21  9 61 90 32]]
(4, 7)
(0, 1)


**Q17**

Write a Python program using NumPy to create a 5x5 matrix filled with random floats between 0 and 1. Replace the maximum value in the matrix with 0 and print the original and modified matrices.



In [5]:
import numpy as np

array = np.random.sample(25).reshape(5,5)

print(array)

index = np.unravel_index(np.argmax(array,axis=None),array.shape)
array[index] = 0

print(array)


[[0.49204194 0.32696246 0.71660131 0.44805058 0.57956642]
 [0.48294002 0.34196851 0.0888912  0.01138279 0.89026598]
 [0.20259061 0.59292614 0.60895445 0.67990556 0.73937125]
 [0.32393774 0.9808985  0.14355387 0.27870991 0.00694372]
 [0.47670311 0.18552867 0.14006159 0.07891295 0.94170788]]
[[0.49204194 0.32696246 0.71660131 0.44805058 0.57956642]
 [0.48294002 0.34196851 0.0888912  0.01138279 0.89026598]
 [0.20259061 0.59292614 0.60895445 0.67990556 0.73937125]
 [0.32393774 0.         0.14355387 0.27870991 0.00694372]
 [0.47670311 0.18552867 0.14006159 0.07891295 0.94170788]]


**Q18**

Given the following NumPy code, predict the output of the code:



import numpy as np



A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]



B[0, 0] = 100

print(A)

In [6]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = A[1:3,0:2]  #Should be 0 to 2 and not 1 to 3, but may 1:2:0, so B = [[4,5,6],[7,8,9],[1,2,3]]
B[0,0] = 100  #B = [[4,5,6],[7,8,9],[1,2,3]], so 4 got replaced by 100?
print(A)      #A = [[1,2,3],[100,5,6],[7,8,9]]

[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


**Q19**

Write a Python program using NumPy to create a 1D array of 20 elements with random integers between 1 and 100. Calculate the number of even and odd elements in the array and print the result.

In [9]:
import numpy as np

array = np.random.randint(1,100,20)
filter_even = (array%2 == 0)
filter_odd = (array%2 == 1)
print(array)
print(filter_even.sum())
print(filter_odd.sum())

[50 90 64 29 67 20 41  5 18 52  4 63 75 78 54 94 34 53 41 86]
12
8


**Q20**

 Given the following NumPy code, predict the output of the code:



import numpy as np



A = np.arange(1, 17).reshape(4, 4)

B = A[:, ::-1]



print(B)

In [10]:
import numpy as np
A = np.arange(1,17).reshape(4,4)  #4x4 matrix, with 1 to 16
B = A[:,::-1]   #Reverse column
print(B)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


**Q21**

Write a Python program using NumPy to create a 2D array of size 8x8, where the outer border elements are set to 1 and the inner elements are set to 0. Print the resulting array.

In [14]:
import numpy as np

array = np.zeros(64).reshape(8,8)

for ix,iy in np.ndindex(array.shape):
  if((ix==0) or (iy==0) or (iy==7) or (ix==7)):
    array[ix][iy] = 1

print(array)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
