**Q1**

What will be the shape of the following NumPy array?



import numpy as np

arr = np.random.randint(1, 101, 100).reshape(10, -1)

In [ ]:
import numpy as np

arr = np.random.randint(1, 101, 100).reshape(10, -1)
#The -1 in the reshape, means size should be inferred based on the original size and specified dimensions
# 100 elements are reshaped into 10 rows, resulting in 10x10

print(arr.shape)

(10, 10)


**Q2**

What is the result of the following code?



import numpy as np

A = np.array([1, 2, 3])

B = A * 2

In [ ]:
A = np.array([1, 2, 3])

B = A * 2

print(B)

[2 4 6]


**Q3**

What does the following code output?



import numpy as np

matrix = np.eye(4)

result = np.diagonal(matrix)

print(result)

In [ ]:
matrix = np.eye(4)

result = np.diagonal(matrix)

print(result)

[1. 1. 1. 1.]


**Q4**

What is the result of the following code?



import numpy as np

A = np.array([[1, 2], [3, 4]])

B = A.T

In [ ]:
A = np.array([[1, 2], [3, 4]])

B = A.T
print(B)

[[1 3]
 [2 4]]


**Q5**

Which function can be used to concatenate two NumPy arrays horizontally?
p.hstack()

And not p.vstack(), np.concatenate, or np.append()

**Q6**

Which of the following functions can be used to compute the element-wise multiplication of two arrays A and B?

np.multiply(A,B)

**Q7**

What is the result of the following code?



import numpy as np

A = np.array([10, 20, 30, 40])

mask = (A >= 20) & (A <= 30)

B = A[mask]

In [ ]:
A = np.array([10, 20, 30, 40])

mask = (A >= 20) & (A <= 30)

B = A[mask]
print(B)

[20 30]


**Q9**

Which of the following NumPy functions will return the indices of the minimum and maximum values in an array?


np.argmin(), np.argmax()

**Q10**

What is the output of the following code?



import numpy as np

arr = np.arange(1, 10).reshape(3, 3)

result = np.trace(arr)

print(result)

In [ ]:
arr = np.arange(1, 10).reshape(3, 3)

result = np.trace(arr)  #trace gives sum along diagnal
print(arr)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


**Q11**

What is the output of the following code?



import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.cross(arr1, arr2)

print(result)

[-3  6 -3]


**Q12**

Write a Python program using NumPy to create a 5x5 matrix filled with random integers between 1 and 100. Calculate the mean and standard deviation of the matrix and print them.

In [ ]:
q12 = np.random.randint(1,100,25).reshape(5,5)
print(q12)
print(q12.mean()) #mean
print(q12.std())

[[74 30 43 81 33]
 [73 15 74 11 25]
 [26 37 38 53 12]
 [20 92 72 29  1]
 [ 9 46 11 25 84]]
40.56
26.72389193212695


**Q13**

Using NumPy, create a 5x5 identity matrix and add a scalar value of 5 to it. Multiply the resulting matrix with a 5x1 column vector filled with random integers between 1 and 10. Print the resulting vector.

In [3]:
import numpy as np

matrix1 = np.eye(5)
matrix1 = matrix1 + 5
matrix2 = np.random.randint(1,10,5)
matrix3 = np.matmul(matrix1,matrix2)
print(matrix3)

[ 97.  97. 102.  96. 102.]


**Q14**

Write a Python program using NumPy to create two 3x3 matrices filled with random integers between 1 and 100. Compute their element-wise multiplication, and print the resulting matrix.

In [6]:
import numpy as np

matrix1 = np.random.randint(1,100,9).reshape(3,-1)
matrix2 = np.random.randint(1,100,9).reshape(3,-1)
matrix3 = np.multiply(matrix1,matrix2)
print(matrix3)

[[1034  135 2490]
 [1288 3132 2880]
 [ 690  752 2964]]
