**Using numpy to create an array**

In [6]:
import numpy as np
arr0 = np.array([120,50,100])
print(arr0)
print(type(arr0))
print(arr0.size)
print(arr0.ndim)
print(arr0.dtype)

[120  50 100]
<class 'numpy.ndarray'>
3
1
int64


**Using numpy for 2D**

In [13]:
import numpy as np 

arr2 = np.array([[1,2,3],[4,5,6]])  #2-d array, 2*3
print(arr2)

arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

a=np.array(42) #0-d, single number
b=np.array([42])  #1-d array
c=np.array([1,2,3,4]) #1-d array
d = np.array([[1,2,3],[4,5,6]])
e = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

print(e.shape)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
1
2
3
(2, 2, 3)


**Accessing array elements**


In [20]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr[0])

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print('2nd element in 1st row=', arr2[0][1])
print('2nd element from end in 1st row=', arr2[0][-2])

1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element in 1st row= 2
2nd element from end in 1st row= 4


**Slicing**

In [23]:
import numpy as np

arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr2[4:])

print(arr2[:4])

print(arr2[-3:-1])

print(arr2[1:5:2])  #exclusive index from 1 to 5, step 2

print(arr2[::2])  #every 2nd element from 1

[ 5  6  7  8  9 10]
[1 2 3 4]
[8 9]
[2 4]
[1 3 5 7 9]


**Slicing to get another array**

Sliced array reflects changes of parent array

In [29]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

#sliced array
arr2 = arr[0:2,2]
print(arr2)
arr[1][2]=30
print(arr2)

arr3 = arr2[0:1]
print(arr3)

[7 8 9]
[3 8]
[ 3 30]
[3]


**Slicing to get a copy**

In [31]:
import numpy as np

arr=np.array([1,2,3,4,5])
arr2 = arr.copy()
print(arr2)
arr[1]=10
print(arr)
print(arr2)

[1 2 3 4 5]
[ 1 10  3  4  5]
[1 2 3 4 5]
